port: 7880
bind_addresses:
    - ""
rtc:
    tcp_port: 7881
    port_range_start: 50000
    port_range_end: 60000
    use_external_ip: false
    enable_loopback_candidate: false
redis:
    address: 192.168.79.50:6379
    # address: 192.168.31.78:6379
    username: ""
    password: ""
    db: 0
    use_tls: false
    sentinel_master_name: ""
    sentinel_username: ""
    sentinel_password: ""
    sentinel_addresses: []
    cluster_addresses: []
    max_redirects: null
turn:
    enabled: false
    domain: local.ospfy.com
    tls_port: 5349
    udp_port: 3478
    external_tls: true
keys:
    API2CkexsWtNdB5: 35pzHzV9pNXOSzMyCJHniWKrnyfu1hKU8TBKCz7r0yU
